name: Rust

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '*.*.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  TEST_CONFIG: ${{ secrets.TEST_CONFIG }}

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  run-unit-tests-multidispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: multi_dispatcher
        run: cargo test

  test-app:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: export config
      run: echo "$TEST_CONFIG" > .github/config.txt && cat .github/config.txt | base64 -d > .github/testconfig.yaml
    - name: Run app init
      run: cargo run -- --init --config=.github/testconfig.yaml
    - name: Run app scan
      run: cargo run -- --scan --config=.github/testconfig.yaml
